### PR TITLE
feat: added uml doc

### PR DESCRIPTION
**Pull request by CL-SHLOMIKONCHA**

### CODE REVIEW

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml

**Comment by CL-SHLOMIKONCHA** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<mxfile host="app.diagrams.net" modified="2020-10-14T07:32:43.694Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" etag="3XUXEgTstRgeLXFuTvK_" version="13.7.9"><diagram id="4hkAA6pZJcqtaLvKymFX" name="Page-1">5VpRc6M2EP41nsk9XAYEGPsx59jtTKedu/HDtY8qyKCzQJwQsd1fX8lINiCcBAcTx5dkMmglFmm//Va7gpEzS7a/MZjFf9IQkRGwwu3IeRwBYLsAjOSfFe5Kie/4pSBiOFSDjoIl/g8poaWkBQ5RXhvIKSUcZ3VhQNMUBbwmg4zRTX3YipL6UzMYIUOwDCAxpd9xyONSOgH+Uf47wlGsn2yPp2VPAvVgtZI8hiHdVETOfOTMGKW8vEq2M0Sk8bRdyvsWJ3oPE2Mo5a+5wXvgUy/GzJ8v/pp/+zbPrJ8/PistT5AUasFqsnynLYDS8EEaUrRSmgrhl5gnRLRscVmORqFhxOOsNGqQRYg/MxVwsIlwJkQTxNlO3Lc5Wt1TlowrBtcyhgjk+Kk+DajAjw7qDk/4SrGYILC0o3peeYtyU0/7n1aR04IFSN1VtXJT0diqKbKbiko7GIrERWXZR9EexA6AAgPQP+BqDQ1UGS3SEElNloBxE2OOlhkMZO9GMLkN5SfEONo+j7OJn77BOmGXCr4HWRVg1zqNZc14XS3lDOT67+XSzrQnl24qsr1hXdo1gJpvMyp8kX3+TtkasXd3bse9Nuf2Ojl3QGCe46BulxUmZEYJZfvhzsqTv0Kec0bXSPcoXnw0MgDn3PjuvaDowmQYvx3YOoACWmv/I3pCmMd72rwtvvW8F4NpT4HLUHRhrCaXxOrDMQ70xbimogujOO2EooqHNSbdBJ5jp6d0oqlo6HRCz7sC6IwmCU2FbMkpkwXheycU3sSu2+jdEwq7W6XYMZjV7SuMxHZ/y8b9dAy04B+p5d7ydPtxWx3+uKu2viKGxboRU8LXkusVZao9vqqoeu7e6Fp1Ra4/eRULBcBwVxmWyQH56Qm7dvuET86rMd517YbvljPoNySYtSDBOUepWJgV7AKCA0iIXDan4t/PAhVmjBBs58/5u9oZqmm1EkGCo1SSRjijdNkvMnbIRz6ojgSHoXxMa+Spc6eH4GNPGpBZLcFn0uLjzY25v+BjloABTfMiEShYCcpzEbPvOMzXn0R7xWjyC4DUzIrGwADpUJsMA1IPNefFS5OhojS4b4axs7PfF1VdOl8yS06G5PmLDI55EQSCf3eByKAwF/RbrCAmBUN3ISJiA/50wwx0G7gAM0wCzdJhGOi/nYE1nn3caqWZRjj+9Dz+NasVQ9Gl2WceIhRZCDmS7MsYjZign5xOGu6BhrwQzTGRHPuXiatIXimajqTrLeQeWZL0dsnp6pRBw+a1kNMadHs0zxGWsViPhE2+lZTH2AqdBSYyscl3IgVNDIyGrkUn4NpqUWBW8D1mGtcf2uqufXZqMfFfUHTpV5VnvXy+vZO1id/TyVpT0dAnaxq/CqA5fJKhLMrW0e1uNr4GTBNJp8wV//GH3GuAmbLjVSU9sES6nsn0/HYxcRuvZN2WQ4y28rj5Oq8/TMz9X8BRVlEij9vnZzgVLLHkQcYNA+PUgXFagHGHJIvXrWoyPwRpM9H17jZN+5+dPhzq3Y6VUecT5KbDqOeceSIsmsdv7srhxy8Xnfn/</diagram></mxfile>

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml

**Comment by CL-SHLOMIKONCHA** [comment]
Untitled Diagram

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml

**Review by asafMasa — APPROVED** [review]

**Comment by CL-SHLOMIKONCHA** [comment]
uml_worker

**Pull request merged**
