### PR TITLE
chore: updated uml

### PR DESCRIPTION
**Pull request by CL-SHLOMIKONCHA**

### CODE REVIEW

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml_v2

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml_v2

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml_v2

**Comment by CL-SHLOMIKONCHA** [comment]
worker_uml_v2

**Review by asafMasa — APPROVED** [review]

**Pull request merged**
